### **Beginner**
----
- Print the shape of the array.
- Print the data type.
- Print the total number of elements.
- Print only the Sales column.
- Print only the Profit column.
- Print the first 5 months.
- Print the last 3 months.
- Print the Advertising and Profit columns only.
- Find the maximum Sales.
- Find the minimum Profit.
- Find the average Sales.
- Find the total Profit earned in the year.
- Find the month with the highest Sales.
- Find the month with the lowest Advertising Cost.
- Find the average number of new customers.
- Find the sum of each column.
- Find the average of each column.
- Increase all Sales by 10%.
- Increase all Advertising costs by 5%.
- Print only the months where Profit > 7000.

In [3]:
import numpy as np

# Column 0 → Sales
# Column 1 → Advertising Cost
# Column 2 → New Customers
# Column 3 → Profit

df = np.array([
    [12000, 2000, 150, 3200],
    [15000, 2500, 180, 4200],
    [17000, 3000, 210, 5100],
    [16000, 2800, 205, 4800],
    [19000, 3500, 240, 6200],
    [21000, 3800, 260, 7000],
    [23000, 4000, 290, 7800],
    [22000, 3900, 275, 7400],
    [24000, 4200, 300, 8200],
    [26000, 4500, 330, 9100],
    [28000, 4700, 350, 9800],
    [30000, 5000, 380, 11000]
])

In [ ]:
# Print the shape of the array.

df.shape

(12, 4)

In [ ]:
# Print the data type.

df.dtype

dtype('int64')

In [ ]:
# Print the total number of elements.

df.size

48

In [ ]:
# Print only the Sales column.

df[:, 0]

array([12000, 15000, 17000, 16000, 19000, 21000, 23000, 22000, 24000,
       26000, 28000, 30000])

In [ ]:
# Print only the Profit column.

df[:, -1]

array([ 3200,  4200,  5100,  4800,  6200,  7000,  7800,  7400,  8200,
        9100,  9800, 11000])

In [ ]:
# Print the first 5 months.

df[0: 5]

array([[12000,  2000,   150,  3200],
       [15000,  2500,   180,  4200],
       [17000,  3000,   210,  5100],
       [16000,  2800,   205,  4800],
       [19000,  3500,   240,  6200]])

In [ ]:
# Print the last 3 months.

df[-3:]

array([[26000,  4500,   330,  9100],
       [28000,  4700,   350,  9800],
       [30000,  5000,   380, 11000]])

In [ ]:
# Print advertising and profit columns only

df[:, 1:4]

array([[ 2000,   150,  3200],
       [ 2500,   180,  4200],
       [ 3000,   210,  5100],
       [ 2800,   205,  4800],
       [ 3500,   240,  6200],
       [ 3800,   260,  7000],
       [ 4000,   290,  7800],
       [ 3900,   275,  7400],
       [ 4200,   300,  8200],
       [ 4500,   330,  9100],
       [ 4700,   350,  9800],
       [ 5000,   380, 11000]])

In [ ]:
# Print the maximum sales value.

np.max(df[:, 0])

np.int64(30000)

In [ ]:
# Print the minimum profit value.

np.min(df[:, 3])

np.int64(3200)

In [ ]:
# Print the average sales value.

np.average(df[:, 0])

np.float64(21083.333333333332)

In [ ]:
# Print the total profit value.

np.sum(df[:, -1])

np.int64(83800)

In [ ]:
# Find the month with the highest sales.

highest_sales_month = np.argmax(df[:, 0])
highest_sales_month

np.int64(11)

In [ ]:
# Find the month with the lowest advertising cost.

np.argmin(df[:, 1])

np.int64(0)

In [ ]:
# Print the average number of new customers.

np.average(df[:, 2])

np.float64(264.1666666666667)

In [37]:
# Find the sum of each column

print(np.sum(df, axis=0))

# Find the sum of each row


print(np.sum(df, axis=1))

[253000  43900   3170  83800]
[17350 21880 25310 23805 28940 32060 35090 33575 36700 39930 42850 46380]


In [38]:
# Find the average of each column

print(np.average(df, axis=0))

[21083.33333333  3658.33333333   264.16666667  6983.33333333]


In [40]:
# Increase all sales by 10% 

df[:, 0] = df[:, 0] * 1.10
print(df[:, 0])

[14520 18150 20570 19360 22990 25410 27830 26620 29040 31460 33880 36300]


In [41]:
# Increase all advertising costs by 5%

df[:, 1] = df[:, 1] * 1.05
print(df[:, 1])

[2100 2625 3150 2940 3675 3990 4200 4095 4410 4725 4935 5250]


In [ ]:
# Print only the months where Profit > 7000.

print(df[df[:, 3] > 7000])

[[27830  4200   290  7800]
 [26620  4095   275  7400]
 [29040  4410   300  8200]
 [31460  4725   330  9100]
 [33880  4935   350  9800]
 [36300  5250   380 11000]]
