### **NumPy **Exercise** Roadmap**
#### **🟢 Level 1 — Beginner (15 **Exercise**s)**

**Learn how NumPy arrays work.**

****Exercise** 1**

- Print the shape.

****Exercise** 2**

- Print number of rows.

**Exercise** 3

- Print number of columns.

**Exercise** 4

- Print the first row.

**Exercise** 5

- Print the last row.

**Exercise** 6

- Print only Monthly Income column.

**Exercise** 7

- Print only Orders column.

**Exercise** 8

- Print first five customers.

**Exercise** 9

- Print last five customers.

**Exercise** 10

- Print Age and Income together.

**Exercise** 11

- Print customers whose age is greater than 30.

**Exercise** 12

- Print customers from Karachi.

**Exercise** 13

- Print subscribed customers.

**Exercise** 14

- Print customers with income above 80,000.

**Exercise** 15

- Print customers having more than 20 orders.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [15]:
df = pd.read_csv("../cleaned_business_sales.csv")
df.head()

,Customer_ID,Age,Gender,City,Monthly_Income,Orders,Average_Order_Value,Discount_Used,Returned_Items,Satisfaction,Subscription
0,1001,22,0,0,45000,12,1800,1,1,4,0
1,1002,31,1,1,72000,20,2500,0,0,5,1
2,1003,27,0,2,55000,15,2100,1,2,3,0
3,1004,45,1,0,98000,30,3200,0,1,5,1
4,1005,35,0,3,68000,18,2400,1,0,4,1


In [17]:
## Converting the df in to the numpy array
data = df.to_numpy()

## **Each Code Cell Solved One Excercise One BY One**

In [28]:
## Print the shape of the dataset using the numpy

data.shape

(20, 11)

In [22]:
# Print number of rows and columns in the dataset using the numpy 

print("Number of rows:", data.shape[0])
print("Number of columns:", data.shape[1])

Number of rows: 20
Number of columns: 11


In [24]:
# Print the first and last row

print("First row:", data[0])
print("Last row:", data[-1])


First row: [ 1001    22     0     0 45000    12  1800     1     1     4     0]
Last row: [ 1020    42     1     3 91000    27  3150     0     0     5     1]


In [33]:
print("Monthly_Income:\n", data[:, 4])

Monthly_Income:
 [ 45000  72000  55000  98000  68000  51000  89000  47000  76000  62000
  53000  94000  70000  43000 110000  49000  65000  82000  58000  91000]


In [34]:
print("Orders:\n", data[:, 5])

Orders:
 [12 20 15 30 18 14 26 10 22 17 13 28 21  9 35 11 19 24 16 27]


In [39]:
## Print First five rows of the dataset using the numpy
print("First five rows:\n", data[:5])

First five rows:
 [[ 1001    22     0     0 45000    12  1800     1     1     4     0]
 [ 1002    31     1     1 72000    20  2500     0     0     5     1]
 [ 1003    27     0     2 55000    15  2100     1     2     3     0]
 [ 1004    45     1     0 98000    30  3200     0     1     5     1]
 [ 1005    35     0     3 68000    18  2400     1     0     4     1]]


In [40]:
## Print Last five rows of the dataset using the numpy
print("Last five rows:\n", data[-5:])

Last five rows:
 [[ 1016    26     1     7 49000    11  1750     1     1     3     0]
 [ 1017    32     0     1 65000    19  2350     0     0     4     1]
 [ 1018    39     1     2 82000    24  2950     0     1     5     1]
 [ 1019    30     0     0 58000    16  2200     1     2     3     0]
 [ 1020    42     1     3 91000    27  3150     0     0     5     1]]


In [41]:
## Print Age and Monthly_Income columns together

print("Age and Monthly_Income columns:\n", data[:, [1, 4]])

Age and Monthly_Income columns:
 [[    22  45000]
 [    31  72000]
 [    27  55000]
 [    45  98000]
 [    35  68000]
 [    29  51000]
 [    41  89000]
 [    24  47000]
 [    38  76000]
 [    33  62000]
 [    28  53000]
 [    40  94000]
 [    36  70000]
 [    23  43000]
 [    50 110000]
 [    26  49000]
 [    32  65000]
 [    39  82000]
 [    30  58000]
 [    42  91000]]


In [42]:
## Print customers whose age is greater than 30 
print("Customers with age greater than 30:\n", data[data[:, 1] > 30])

Customers with age greater than 30:
 [[  1002     31      1      1  72000     20   2500      0      0      5
       1]
 [  1004     45      1      0  98000     30   3200      0      1      5
       1]
 [  1005     35      0      3  68000     18   2400      1      0      4
       1]
 [  1007     41      0      1  89000     26   3000      0      0      5
       1]
 [  1009     38      0      2  76000     22   2800      0      1      4
       1]
 [  1010     33      1      0  62000     17   2300      1      0      4
       1]
 [  1012     40      1      1  94000     28   3100      0      0      5
       1]
 [  1013     36      0      0  70000     21   2600      1      1      4
       1]
 [  1015     50      0      0 110000     35   3600      0      0      5
       1]
 [  1017     32      0      1  65000     19   2350      0      0      4
       1]
 [  1018     39      1      2  82000     24   2950      0      1      5
       1]
 [  1020     42      1      3  91000     27   3150      0    

In [ ]:
## Print customers from Karachi

print("Customers from Karachi:\n", data[data[:, 3] == 0])

Customers from Karachi:
 [[  1001     22      0      0  45000     12   1800      1      1      4
       0]
 [  1004     45      1      0  98000     30   3200      0      1      5
       1]
 [  1008     24      1      0  47000     10   1700      1      3      2
       0]
 [  1010     33      1      0  62000     17   2300      1      0      4
       1]
 [  1013     36      0      0  70000     21   2600      1      1      4
       1]
 [  1015     50      0      0 110000     35   3600      0      0      5
       1]
 [  1019     30      0      0  58000     16   2200      1      2      3
       0]]


In [48]:
## Print subscribed customers

print("Subscribed customers:\n", data[data[:, 10] == 1])


Subscribed customers:
 [[  1002     31      1      1  72000     20   2500      0      0      5
       1]
 [  1004     45      1      0  98000     30   3200      0      1      5
       1]
 [  1005     35      0      3  68000     18   2400      1      0      4
       1]
 [  1007     41      0      1  89000     26   3000      0      0      5
       1]
 [  1009     38      0      2  76000     22   2800      0      1      4
       1]
 [  1010     33      1      0  62000     17   2300      1      0      4
       1]
 [  1012     40      1      1  94000     28   3100      0      0      5
       1]
 [  1013     36      0      0  70000     21   2600      1      1      4
       1]
 [  1015     50      0      0 110000     35   3600      0      0      5
       1]
 [  1017     32      0      1  65000     19   2350      0      0      4
       1]
 [  1018     39      1      2  82000     24   2950      0      1      5
       1]
 [  1020     42      1      3  91000     27   3150      0      0      5
   

In [49]:
## Print customers with monthly income greater than 80, 000
print("Customers with monthly income greater than 80,000:\n", data[data[:, 4] > 80000])

Customers with monthly income greater than 80,000:
 [[  1004     45      1      0  98000     30   3200      0      1      5
       1]
 [  1007     41      0      1  89000     26   3000      0      0      5
       1]
 [  1012     40      1      1  94000     28   3100      0      0      5
       1]
 [  1015     50      0      0 110000     35   3600      0      0      5
       1]
 [  1018     39      1      2  82000     24   2950      0      1      5
       1]
 [  1020     42      1      3  91000     27   3150      0      0      5
       1]]


In [50]:
## Print customers have more than 20 orders

print("Customers with more than 20 orders:\n", data[data[:, 5] > 20])

Customers with more than 20 orders:
 [[  1004     45      1      0  98000     30   3200      0      1      5
       1]
 [  1007     41      0      1  89000     26   3000      0      0      5
       1]
 [  1009     38      0      2  76000     22   2800      0      1      4
       1]
 [  1012     40      1      1  94000     28   3100      0      0      5
       1]
 [  1013     36      0      0  70000     21   2600      1      1      4
       1]
 [  1015     50      0      0 110000     35   3600      0      0      5
       1]
 [  1018     39      1      2  82000     24   2950      0      1      5
       1]
 [  1020     42      1      3  91000     27   3150      0      0      5
       1]]


In [52]:
print("======= Level 1 Completed======= ")

======= Level 1 Completed======= 
