##### **Array Creation Ways**

In [ ]:
## Creating Arrays
import numpy as np

np.array() # Create an array from a list or tuple

np.zeros() # Create an array of zeros

np.ones() # Create an array of ones

np.empty() # Create an empty array (uninitialized values)

np.full() # Create an array filled with a specified value

np.arange() # Create an array with a range of values

np.linspace() # Create an array with evenly spaced values over a specified interval

np.eye() # Create a 2-D array with ones on the diagonal and zeros elsewhere

np.identity() # Create a square identity matrix

##### **Array Attributes**

In [ ]:
## Array Attributes

np.ndim # Number of dimensions of the array

np.shape # Shape of the array (tuple of dimensions)

np.size # Total number of elements in the array

np.dtype # Data type of the array elements

np.itemsize # Size in bytes of each element in the array

np.nbytes # Total size in bytes of the array

#### **Array Practice**

In [ ]:
# 1D Array Creation and Manipulation
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("Original 1D Array:", array_1d)

# Accessing elements
print("First element:", array_1d[0])

# Modifying elements
array_1d[2] = 10
print("Modified 1D Array:", array_1d)

# Array Slicing
sliced_array = array_1d[1:4]
print("Sliced Array (elements 1 to 3):", sliced_array)

In [53]:
import numpy as np

# Sample arrays to ensure the code executes successfully
zeros_array = np.zeros((3, 4))
ones_array = np.ones((3, 4))
arange_array = np.array([1, 1, 2, 2, 3, 3, 4, 4])
mean_array = np.mean(arange_array)
sqrt_array = np.sqrt(arange_array)
random_array = np.random.rand(3, 4)  # Random values in a 3x4 array
identity_matrix = np.identity(3)  # 3x3 identity matrix
full_array = np.full((2, 3), 7)  # 2x3 array filled with the value 7


In [54]:
# ==========================================
# SECTION 4: INITIAL ARRAYS & CALCULATIONS
# ==========================================
print("\n" + "=" * 50)
print("SECTION 4: INITIAL ARRAYS & CALCULATIONS")
print("=" * 50)

print("• Zeros Array:")
print(f"  Description: An array entirely populated with 0.0 float values.")
print(zeros_array)
print("\n" + "-" * 30)

print("• Ones Array:")
print(f"  Description: An array entirely populated with 1.0 float values.")
print(ones_array)
print("\n" + "-" * 30)

print("• Arange Array:")
print(f"  Description: A sequence of evenly spaced numeric values.")
print(arange_array)
print("\n" + "-" * 30)

print(f"• Mean of Arange Array:        {mean_array}")
print(f"  Description: The mathematical average of the arange sequence.\n")

print("• Square Root of Arange Array:")
print(f"  Description: Element-wise square root calculations.")
print(sqrt_array)
print("\n" + "-" * 30)

print("• Random Array:")
print(f"  Description: Uniformly distributed random float numbers.")
print(random_array)
print("\n" + "-" * 30)

print("• Identity Matrix:")
print(f"  Description: A square matrix with ones on the main diagonal.")
print(identity_matrix)
print("\n" + "-" * 30)

print("• Full Array:")
print(f"  Description: A matrix filled completely with a specific custom value.")
print(full_array)
print("=" * 50)



SECTION 4: INITIAL ARRAYS & CALCULATIONS
• Zeros Array:
  Description: An array entirely populated with 0.0 float values.
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

------------------------------
• Ones Array:
  Description: An array entirely populated with 1.0 float values.
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

------------------------------
• Arange Array:
  Description: A sequence of evenly spaced numeric values.
[1 1 2 2 3 3 4 4]

------------------------------
• Mean of Arange Array:        2.5
  Description: The mathematical average of the arange sequence.

• Square Root of Arange Array:
  Description: Element-wise square root calculations.
[1.         1.         1.41421356 1.41421356 1.73205081 1.73205081
 2.         2.        ]

------------------------------
• Random Array:
  Description: Uniformly distributed random float numbers.
[[0.58570418 0.72254978 0.1945998  0.76895378]
 [0.78814925 0.1191315  0.3864307  0.11623999]
 [0.35096495 0.30518838 0.12661257 0.97

In [55]:
# ==========================================
# SECTION 1: ARRAY ATTRIBUTES
# ==========================================
print("=" * 50)
print("SECTION 1: PRINTING ARRAY ATTRIBUTES")
print("=" * 50)

print(f"• Number of dimensions (ndim):     {zeros_array.ndim}")
print(f"  Description: Total number of axes (dimensions) in the array.\n")

print(f"• Shape of the array (shape):      {zeros_array.shape}")
print(f"  Description: A tuple showing the size of the array in each dimension.\n")

print(f"• Total number of elements (size): {zeros_array.size}")
print(f"  Description: The total number of elements across all dimensions.\n")

print(f"• Data type of the array (dtype):  {zeros_array.dtype}")
print(f"  Description: The specific data type of the elements in the array.")
print("-" * 50)


# ==========================================
# SECTION 2: STATISTICAL MATHEMATICS
# ==========================================
print("\n" + "=" * 50)
print("SECTION 2: STATISTICAL MATHEMATICS")
print("=" * 50)

print(f"• Mean:               {np.mean(zeros_array)}")
print(f"• Max Value:          {np.max(zeros_array)}")
print(f"• Min Value:          {np.min(zeros_array)}")
print(f"• Sum of Elements:    {np.sum(zeros_array)}")
print(f"• Standard Deviation: {np.std(zeros_array)}")
print(f"• Variance:           {np.var(zeros_array)}")
print("-" * 50)


# ==========================================
# SECTION 3: MATRIX & ARRAY OPERATIONS
# ==========================================
print("\n" + "=" * 50)
print("SECTION 3: MATRIX & ARRAY OPERATIONS")
print("=" * 50)

print("• Dot Product (Zeros and Transposed Ones Array):")
print(np.dot(zeros_array, ones_array.T))
print("\n" + "-" * 30)

print("• Transpose of Zeros Array:")
print(zeros_array.T)
print("\n" + "-" * 30)

print("• Reshaped Zeros Array (2x6):")
print(zeros_array.reshape(2, 6))
print("\n" + "-" * 30)

print("• Concatenated Zeros and Ones Arrays (Axis=0):")
print(np.concatenate((zeros_array, ones_array), axis=0))
print("\n" + "-" * 30)

print("• Split Zeros Array into 3 Parts:")
for i, part in enumerate(np.array_split(zeros_array, 3), 1):
    print(f"  Part {i}:\n{part}")
print("\n" + "-" * 30)

print("• Sorted Ones Array (Flattened):")
print(np.sort(ones_array, axis=None))
print("\n" + "-" * 30)

print(f"• Unique Elements in Arange Array: {np.unique(arange_array)}")
print("\n" + "-" * 30)

print("• Broadcasting Example (Adding 1D array to 2D array):")
print(zeros_array + np.array([1, 2, 3, 4]))
print("=" * 50)


SECTION 1: PRINTING ARRAY ATTRIBUTES
• Number of dimensions (ndim):     2
  Description: Total number of axes (dimensions) in the array.

• Shape of the array (shape):      (3, 4)
  Description: A tuple showing the size of the array in each dimension.

• Total number of elements (size): 12
  Description: The total number of elements across all dimensions.

• Data type of the array (dtype):  float64
  Description: The specific data type of the elements in the array.
--------------------------------------------------

SECTION 2: STATISTICAL MATHEMATICS
• Mean:               0.0
• Max Value:          0.0
• Min Value:          0.0
• Sum of Elements:    0.0
• Standard Deviation: 0.0
• Variance:           0.0
--------------------------------------------------

SECTION 3: MATRIX & ARRAY OPERATIONS
• Dot Product (Zeros and Transposed Ones Array):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

------------------------------
• Transpose of Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

--