In [1]:
import numpy as np 

In [3]:
a = np.array([[1, 2, 3]]) # 1D array with shape (1, 3)
a.shape

(1, 3)

In [4]:
a.ndim

2

In [6]:
len(a.shape) == a.ndim   

True

In [7]:
a.size

3

In [8]:
a.dtype

dtype('int64')

In [9]:
b = a.copy()
b

array([[1, 2, 3]])

In [11]:
a.max()

np.int64(3)

In [12]:
a.min()

np.int64(1)

In [13]:
a.mean()

np.float64(2.0)

In [30]:
a.sort(axis=-1, descending=True)
a

array([[3, 2, 1]])

In [31]:
a.sort(axis=-1, descending=False)
a

array([[1, 2, 3]])

In [35]:
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array with shape (2, 3)

In [38]:
print(c.shape) # (2, 3) 2 = number of rows, 3 = number of columns
print(c.ndim) # 2 (number of dimensions)
print(c.size) # 6 (total number of elements)
print(c.dtype) # int64 (data type)

(2, 3)
2
6
int64


In [45]:
c = c.repeat(10, axis=0) # repeat each row 10 times
print(c)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [46]:
d = np.zeros((3, 4)) # 2D array with shape (3, 4) filled with zeros
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [48]:
e = np.ones((3, 6)) # 2D array with shape (2, 3) filled with ones
print(e)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [52]:
f = np.full((3, 4), 7) # 2D array with shape (3, 4) filled with sevens
print(f)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
g = np.eye(3, 5) # 2D array with shape (3, 5) filled with identity matrix
print(g)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [58]:
h = np.random.rand(3, 4) # 2D array with shape (3, 4) filled with random numbers between 0 and 1
print(h)

[[0.33444321 0.6955751  0.22747142 0.05652246]
 [0.02617222 0.04276838 0.97940229 0.65261912]
 [0.10661557 0.96880771 0.55916967 0.8579225 ]]


In [59]:
i = np.random.randint(0, 10, (3, 4)) # 2D array with shape (3, 4) filled with random integers between 0 and 9
print(i)

[[2 9 3 7]
 [7 7 5 0]
 [3 9 1 3]]


In [63]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Opreations

matrix_c = matrix_a + matrix_b # element-wise addition
print(matrix_c)
matrix_d = matrix_a - matrix_b # element-wise subtraction
print(matrix_d)
matrix_e = matrix_a * matrix_b # element-wise multiplication
print(matrix_e)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [64]:
# Dot product
matrix_f = np.dot(matrix_a, matrix_b) # dot product
print(matrix_f)

[[19 22]
 [43 50]]


In [66]:
matrix_a

array([[1, 2],
       [3, 4]])

In [65]:
matrix_a.transpose()

array([[1, 3],
       [2, 4]])

In [68]:
matrix_a.view()

array([[1, 2],
       [3, 4]])